# Generated by Django 5.2.10 on 2026-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Ex: 123456789', max_length=50, null=True, verbose_name='Facebook Pixel ID')),
                ('gtm_id', models.CharField(blank=True, help_text='Ex: GTM-XXXXXX', max_length=50, null=True, verbose_name='Google Tag Manager ID')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
        migrations.AlterField(
            model_name='rastreamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
