# Generated by Django 5.2.10 on 2026-01-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao_alter_rastreamento_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='autor',
            field=models.CharField(blank=True, help_text='Nome da empresa ou pessoa', max_length=100, null=True, verbose_name='Autor/Publisher'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='descricao_site',
            field=models.TextField(blank=True, help_text='Resumo que aparece no Google (Max 160 caracteres)', max_length=160, null=True, verbose_name='Descrição SEO'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='titulo_site',
            field=models.CharField(default='Meu Site Incrível', help_text='Aparece na aba do navegador e no Google (Max 60-70 caracteres)', max_length=70, verbose_name='Título do Site (Browser)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='url_canonica',
            field=models.URLField(blank=True, help_text='Ex: https://digitalizadordeideias.com.br (Importante para evitar conteúdo duplicado)', null=True, verbose_name='URL Canônica'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='gtm_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Tag Manager ID'),
        ),
    ]
