# Generated by Django 5.2.11 on 2026-02-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracao_autor_configuracao_descricao_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Projeto')),
                ('categoria', models.CharField(blank=True, help_text='Ex: Landing Page, Reabilitação, Tecnologia', max_length=50, verbose_name='Categoria/Tag')),
                ('descricao', models.TextField(help_text='Explique o que foi feito no projeto.', verbose_name='Descrição Detalhada')),
                ('slug', models.SlugField(help_text='Ex: medicina-natural. Usado se não houver URL externa.', unique=True, verbose_name='Slug (Link Interno)')),
                ('imagem_capa', models.ImageField(help_text='Dimensão recomendada: 800x600px', upload_to='portfolio/', verbose_name='Foto do Card')),
                ('url_externa', models.URLField(blank=True, help_text='Se preenchido, o card levará para este link. Se vazio, levará para a subpágina interna.', null=True, verbose_name='URL Externa (Opcional)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Publicado')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Quanto menor o número, mais no topo aparece.')),
            ],
            options={
                'verbose_name': 'Item do Portfólio',
                'verbose_name_plural': 'Itens do Portfólio',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
